import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";
import { GoogleAnalytics } from '@next/third-parties/google' 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Junie Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider> 
        <GoogleAnalytics gaId="G-917YEDS64Y" />
      </body>
    </html>
  );
}
